version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youtandatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - youtanetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: youtanapi:latest
    container_name: youtanapi
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - youtanetwork
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  youtanetwork:
